# Travis CI config

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (secure)
# - DOCKER_PASSWORD (secure)
# - SSH_HOST
# - SSH_USER
# - (automatic encryption keys) (secure)

language: python
python:
- "3.8"

services:
- docker

cache: pip

stages:
- name: test
- name: deploy-registry
  if: type = push
- name: deploy-site
  if: type = push

jobs:
  include:
  # Stage: Testing
  - stage: test
    name: Validate Django project
    install: pip install --upgrade -r requirements/testing.txt
    script: manage/ci/validate-django.sh
  - stage: test
    name: Test
    install: pip install --upgrade -r requirements/testing.txt
    script: manage/ci/test.sh
  # LINTING DISABLED
  #- stage: test
  #  name: Lint
  #  install: pip install --upgrade -r requirements/testing.txt
  #  script: flake8
  - stage: test
    name: Validate Docker image
    install: true # NOP
    script: manage/ci/validate-docker.sh

  # Stage: Deploy to registry
  - stage: deploy-registry
    name: Deploy to registry (bleeding)
    if: (branch = master)
    install: echo "0.0.0-SNAPSHOT+$(TZ=Etc/GMT date "+%Y-%m-%dT%H:%M:%SZ")" > VERSION
    script: manage/ci/deploy-registry.sh bleeding

  # Stage: Deploy to site(s)
  - stage: deploy-site
    name: Deploy to site (bleeding)
    if: (branch = master)
    install:
    - openssl aes-256-cbc -K $encrypted_e179e3e23b24_key -iv $encrypted_e179e3e23b24_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
    - chmod 600 keys/ssh_deploy.key
    script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} bleeding
